"""stories into standalone game

Revision ID: 1ca5bb1e908b
Revises: 10239d3a0a4b
Create Date: 2025-05-04 18:23:13.161807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca5bb1e908b'
down_revision: Union[str, None] = '10239d3a0a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stand_alone_games', sa.Column('story_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stand_alone_games', 'stories', ['story_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stand_alone_games', type_='foreignkey')
    op.drop_column('stand_alone_games', 'story_id')
    # ### end Alembic commands ###
