"""your migration message

Revision ID: 3f89bf60c47c
Revises: 77a9d3f3a647
Create Date: 2025-05-18 22:23:16.658847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f89bf60c47c'
down_revision: Union[str, None] = '77a9d3f3a647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('badges', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'badges')
    op.drop_column('profiles', 'is_premium')
    # ### end Alembic commands ###
