"""Simplify user story and timeline view tracking

Revision ID: a5e0e8625093
Revises: 9b1c9d539e2b
Create Date: 2025-06-06 16:24:44.995101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5e0e8625093'
down_revision: Union[str, None] = '9b1c9d539e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_story_views', sa.Column('is_seen', sa.Boolean(), nullable=True))
    op.add_column('user_story_views', sa.Column('viewed_at', sa.DateTime(), nullable=True))
    op.drop_column('user_story_views', 'view_count')
    op.drop_column('user_story_views', 'last_viewed_at')
    op.drop_column('user_story_views', 'first_viewed_at')
    op.add_column('user_timeline_views', sa.Column('is_seen', sa.Boolean(), nullable=True))
    op.add_column('user_timeline_views', sa.Column('viewed_at', sa.DateTime(), nullable=True))
    op.drop_column('user_timeline_views', 'view_count')
    op.drop_column('user_timeline_views', 'last_viewed_at')
    op.drop_column('user_timeline_views', 'first_viewed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_timeline_views', sa.Column('first_viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_timeline_views', sa.Column('last_viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_timeline_views', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_timeline_views', 'viewed_at')
    op.drop_column('user_timeline_views', 'is_seen')
    op.add_column('user_story_views', sa.Column('first_viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_story_views', sa.Column('last_viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_story_views', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_story_views', 'viewed_at')
    op.drop_column('user_story_views', 'is_seen')
    # ### end Alembic commands ###
