"""your migration message

Revision ID: c8904b504361
Revises: 62175cae8fbe
Create Date: 2025-05-04 03:32:50.770558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8904b504361'
down_revision: Union[str, None] = '62175cae8fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stand_alone_games', sa.Column('game_type', sa.Enum('GUESS_THE_YEAR', 'IMAGE_GUESS', 'FILL_IN_THE_BLANK', name='gametypes'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stand_alone_games', 'game_type')
    # ### end Alembic commands ###
