"""Add timeline bookmarks

Revision ID: d9f5ba4ed1c0
Revises: a5e0e8625093
Create Date: 2025-06-06 17:44:59.688996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f5ba4ed1c0'
down_revision: Union[str, None] = 'a5e0e8625093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_timeline_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timeline_id', sa.Integer(), nullable=True),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timeline_id', name='unique_user_timeline_bookmark')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_timeline_bookmarks')
    # ### end Alembic commands ###
