"""Apply recent model changes

Revision ID: dda7263cbfd4
Revises: 
Create Date: 2025-04-20 13:04:34.632877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda7263cbfd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('timelines', sa.Column('categories', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timelines', 'categories')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
